server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: <jdbc-url/>
    username: <username/>
    password: <password/>
    schema:
    - classpath:db/schema/schema-base.sql
    - classpath:db/schema/schema-user.sql
    data:
    - classpath:db/data-maria.sql
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  redis:
    host: 127.0.0.1
    port: 6379
  mail:
    host: smtp.163.com
    username: <username/>
    # 此处 password 为授权码
    password: <password/>
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: false
  thymeleaf:
    cache: true
  profiles:
    active: prod

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false

###########################
#        AliYun OSS 开发参数(目前仅支持阿里云)
# https://www.aliyun.com/product/oss?spm=5176.8142029.388261.574.e9396d3eKg8j7h
###########################
oss:
  enabled: true
  type: aliyun
  ali-yun:
    bucket-name: <bucket-name/>
    endpoint: <endpoint/>
    secret-access: <secret-access/>
    access-key: <access-key/>

security:
  token:
    filter:
      secret: <256字节加密串/>