server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      validation-query: SELECT 1
      test-while-idle: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: 127.0.0.1
    port: 6379
  profiles:
    active: dev
