spring:
  datasource:
    url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
logging:
  level:
    org.springframework: debug
    in.hocg: debug

security.token.filter.secret: YourSecretNeedsToBeAtLeast256BitsLong